### ISSUE TITLE
Error won't load 

### ISSUE THREAD

**Issue by rakrimes** [LemmaEOF/Kiln#2]
Unknown recipe serializer kiln:firing

nevermind I totally picked the wrong instance in multimc was trying to load it vanilla.

**Comment by LemmaEOF** [comment]
Can you give me some more info? What version of Fabric Loader are you using? Is this singleplayer or multiplayer? If multiplayer, do you have it on both client and server?

**Comment by LemmaEOF** [comment]
Oh just noticed the edit whoops that's why you don't reply from email lol
