### ISSUE TITLE
Kiln doesn't drop as an item when broken with a pickaxe

### ISSUE THREAD

**Issue by Jesse-Goertzen** [LemmaEOF/Kiln#3]
Survival mode, using `kiln-1.1.1+1.16.5`, Minecraft `1.16.5`, Fabric Loader `0.11.2`

**Comment by GekidoLukas** [comment]
Same here. There isn't even a loot table for the block

**Comment by LemmaEOF** [comment]
...could have sworn I fixed that at some point. Did I make a typo?

I'm a bit burnt out on Minecraft at the moment so I'll get to this when I can.
